apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld 
  labels:
    app: helloworld
spec:
  selector:
    matchLabels:
        app: helloworld
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: 369452779141.dkr.ecr.us-east-1.amazonaws.com/helloworld:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
